apiVersion: v1
kind: Service
metadata:
  name: {{ include "zep.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "zep.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zep.fullname" . }}-nlp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "zep.name" . }}-nlp
  ports:
    - protocol: TCP
      port: 5557
      targetPort: 5557

